LLVM_DEPTH = ../..

include $(LLVM_DEPTH)/llvmdefs

SUBDIRS = \
    InstCombine \
    Instrumentation \
    IPO \
    Scalar \
    Vectorize \
    Utils \
	SPIR \
    OpenCLIR

include $(LLVM_DEPTH)/llvmrules
